export enum KeysEnum {
    enter = 'Enter',
    backspace = 'Backspace',
    delete = 'Delete',
    ctrlA = 'Control+A',
    ctrlV = 'Control+V',
    ctrlAMacOs = 'Meta+A',
    ctrlVMacOs = 'Meta+V',
    tab = 'Tab',
    escape = 'Escape',
    arrowDown = 'ArrowDown',
    end = 'End',
    home = 'Home',
    insert = 'Insert',
    pageDown = 'PageDown',
    pageUp = 'PageUp',
    arrowRight = 'ArrowRight',
    arrowUp = 'ArrowUp',
    f = 'f'
}
